export const DIGITAL_ART = {
  artworkId: "",
  price: 0.0,
  category: "",
  productImage: "",
  uploadedImage: null,
  numOfPersons: "",
  materials: [],
  material: "",
  style: "",
  figure: "",
  designerNote: "",
  quantity: 1,
  eachPrice: 0,
  total: 0,
  isPhysicalArt: false,
  size: null,
};

export const PHISICAL_ART = {
  artworkId: "",
  price: 0.0,
  category: "",
  material: "",
  size: null,
  materials: [],
  productImage: "",
  uploadedImage: null,
  numOfPersons: "",
  paintingNote: "",
  designerNote: "",
  quantity: 1,
  eachPrice: 0,
  total: 0,
  isPhysicalArt: true,
};
